server:
  port: 8005


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  application:
    name: face
  cloud:
    nacos:
      discovery:
        #server-addr: 8.136.214.212:8848  #配置nacos地址
        server-addr: localhost:8848  #配置nacos地址
#eureka:
#  client:
#    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true
#    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka  #,http://eureka7002.com:7002/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: payment8001
management:
  endpoints:
    web:
      exposure:
        include: '*'
